companies = [
    {
        "name": "Сбер",
        "desc": "Крупнейший банк и экосистема сервисов, интерес к B2B-решениям и совместным продуктам.",
        "industry": "Финтех / Банк",
        "location": "Москва",
        "logo": "assets/logo/sber - logo.png",
        "email": "info@sberbank.ru",
    },
    {
        "name": "ВТБ",
        "desc": "Универсальный банк, масштабные корпоративные программы и закупки.",
        "industry": "Финтех / Банк",
        "location": "Москва",
        "logo": "assets/logo/vtb.ru.png",
        "email": "info@vtb.ru",
    },
    {
        "name": "Альфа-Банк",
        "desc": "Частный банк с сильной цифровой платформой и SMB-фокусом.",
        "industry": "Финтех / Банк",
        "location": "Москва",
        "logo": "assets/logo/alfabank.ru.png",
        "email": "info@alfabank.ru",
    },
    {
        "name": "Тинькофф",
        "desc": "Онлайн-банк и экосистема, открытые API, эксперименты с ИИ.",
        "industry": "Финтех / Банк",
        "location": "Москва",
        "logo": "assets/logo/tinkoff.ru.png",
        "email": "partners@tinkoff.ru",
    },
]
companies += [
    {
        "name": "Газпром нефть",
        "desc": "Топ-3 нефтяная компания, цифровизация добычи и логистики.",
        "industry": "Нефтегаз / Энергетика",
        "location": "Санкт-Петербург",
        "logo": "assets/logo/gazprom-neft.ru.png",
        "email": "info@gazprom-neft.ru",
    },
    {
        "name": "Роснефть",
        "desc": "Крупнейшая нефтяная компания, масштабные закупки и требования к безопасности.",
        "industry": "Нефтегаз",
        "location": "Москва",
        "logo": "assets/logo/rosneft.ru.png",
        "email": "info@rosneft.ru",
    },
    {
        "name": "Лукойл",
        "desc": "Вертикально интегрированная нефтяная компания с международными практиками.",
        "industry": "Нефтегаз",
        "location": "Москва",
        "logo": "assets/logo/lukoil.ru.png",
        "email": "info@lukoil.com",
    },
    {
        "name": "Сибур",
        "desc": "Крупнейшая нефтехимическая компания, открыта к кооперации с тех-стартапами.",
        "industry": "Нефтехимия",
        "location": "Москва",
        "logo": "assets/logo/sibur.ru.png",
        "email": "info@sibur.ru",
    },
    {
        "name": "Яндекс",
        "desc": "Экосистема поиска, карт, доставки и ИИ-сервисов.",
        "industry": "ИТ / Интернет-сервисы",
        "location": "Москва",
        "logo": "assets/logo/yandex.ru.png",
        "email": "partners@yandex.ru",
    },
    {
        "name": "VK",
        "desc": "Социальные сети, видео, облачные и образовательные платформы.",
        "industry": "ИТ / Соцсети",
        "location": "Москва",
        "logo": "assets/logo/vk.com.png",
        "email": "b2b@vk.company",
    },
    {
        "name": "1С",
        "desc": "Разработчик платформы учёта и ERP, сильная экосистема франчайзи.",
        "industry": "Софт для бизнеса",
        "location": "Москва",
        "logo": "assets/logo/1c.ru.png",
        "email": "partner@1c.ru",
    },
    {
        "name": "Kaspersky",
        "desc": "Вендор ИБ с фокусом на B2B и критическую инфраструктуру.",
        "industry": "Кибербезопасность",
        "location": "Москва",
        "logo": "assets/logo/kaspersky.ru.png",
        "email": "partners@kaspersky.com",
    },
]
companies += [
    {
        "name": "Ростелеком",
        "desc": "Крупнейший провайдер связи и ИТ-услуг для бизнеса и государства.",
        "industry": "Телеком / ИТ-инфраструктура",
        "location": "Москва",
        "logo": "assets/logo/rt.ru.png",
        "email": "partner@rt.ru",
    },
    {
        "name": "МТС",
        "desc": "Оператор связи и цифровая экосистема, корпоративные решения.",
        "industry": "Телеком / ИТ",
        "location": "Москва",
        "logo": "assets/logo/mts.ru.png",
        "email": "b2b@mts.ru",
    },
    {
        "name": "МегаФон",
        "desc": "Оператор федерального уровня с развитой B2B-линейкой.",
        "industry": "Телеком",
        "location": "Москва",
        "logo": "assets/logo/megafon.ru.png",
        "email": "partners@megafon.ru",
    },
    {
        "name": "Билайн",
        "desc": "Оператор связи, развивает платформенные сервисы для бизнеса.",
        "industry": "Телеком / Цифровые сервисы",
        "location": "Москва",
        "logo": "assets/logo/beeline.ru.png",
        "email": "b2b@beeline.ru",
    },
    {
        "name": "Ozon",
        "desc": "Маркетплейс с собственной логистикой и финтех-сервисами.",
        "industry": "E-commerce / Маркетплейс",
        "location": "Москва",
        "logo": "assets/logo/ozon.ru.png",
        "email": "partners@ozon.ru",
    },
    {
        "name": "Wildberries",
        "desc": "Массовый маркетплейс с широкой аудиторией.",
        "industry": "E-commerce / Маркетплейс",
        "location": "Москва",
        "logo": "assets/logo/wildberries.ru.png",
        "email": "partners@wildberries.ru",
    },
    {
        "name": "Яндекс Маркет",
        "desc": "Платформа для продавцов с экосистемой сервисов.",
        "industry": "E-commerce",
        "location": "Москва",
        "logo": "assets/logo/market.yandex.ru.png",
        "email": "partner@market.yandex.ru",
    },
    {
        "name": "Авито",
        "desc": "Лидер объявлений, сильный маркетинг и инструменты для бизнеса.",
        "industry": "Классифайды / Маркетплейс",
        "location": "Москва",
        "logo": "assets/logo/avito.ru.png",
        "email": "partners@avito.ru",
    },
]
companies += [
    {
        "name": "Циан",
        "desc": "Поиск жилья и коммерческой недвижимости.",
        "industry": "Недвижимость / Классифайды",
        "location": "Москва",
        "logo": "https://logo.clearbit.com/cian.ru?size=256",
        "email": "b2b@cian.ru",
    },
    {
        "name": "HeadHunter",
        "desc": "Платформа подбора персонала и HR-аналитики.",
        "industry": "HR-тех",
        "location": "Москва",
        "logo": "assets/logo/hh.ru.png",
        "email": "partner@hh.ru",
    },
    {
        "name": "Яндекс Еда",
        "desc": "Сервис доставки с широкой сетью партнёров.",
        "industry": "Фудтех / Доставка",
        "location": "Москва",
        "logo": "assets/logo/eda.yandex.ru.png",
        "email": "partner@eda.yandex.ru",
    },
    {
        "name": "Самокат",
        "desc": "Даркстор-сеть, активные маркетинговые эксперименты.",
        "industry": "Быстрая доставка / E-grocery",
        "location": "Санкт-Петербург",
        "logo": "assets/logo/samolet.ru.png",
        "email": "partners@samokat.tech",
    },
    {
        "name": "СДЭК",
        "desc": "Частный оператор экспресс-доставки.",
        "industry": "Логистика",
        "location": "Новосибирск",
        "logo": "assets/logo/cdek.ru.png",
        "email": "partners@cdek.ru",
    },
    {
        "name": "Почта России",
        "desc": "Национальный почтовый оператор с широкой сетью.",
        "industry": "Логистика / Публичные услуги",
        "location": "Москва",
        "logo": "assets/logo/pochta.ru.png",
        "email": "b2b@russianpost.ru",
    },
    {
        "name": "Selectel",
        "desc": "Независимый провайдер ЦОД и облаков.",
        "industry": "Облако / Дата-центры",
        "location": "Санкт-Петербург",
        "logo": "assets/logo/selectel.ru.png",
        "email": "sales@selectel.ru",
    },
    {
        "name": "СКБ Контур",
        "desc": "Сервисы для бизнеса и государства.",
        "industry": "SaaS / Учёт и отчётность",
        "location": "Екатеринбург",
        "logo": "assets/logo/kontur.ru.png",
        "email": "partner@skbkontur.ru",
    },
]
companies += [
    {
        "name": "2ГИС",
        "desc": "Карты и справочник компаний с B2B-кейсами.",
        "industry": "Картография / Навигация",
        "location": "Новосибирск",
        "logo": "assets/logo/2gis.ru.png",
        "email": "partners@2gis.ru",
    },
    {
        "name": "Инвитро",
        "desc": "Сеть лабораторий, активный маркетинг и франчайзинг.",
        "industry": "Меддиагностика / Лаборатории",
        "location": "Москва",
        "logo": "assets/logo/invitro.ru.png",
        "email": "b2b@invitrorus.ru",
    },
    {
        "name": "МГУ им. М.В. Ломоносова",
        "desc": "Университет мирового уровня, интерес к индустриальным кейсам.",
        "industry": "Вуз / Исследования",
        "location": "Москва",
        "logo": "assets/logo/msu.ru.png",
        "email": "partners@msu.ru",
    },
    {
        "name": "МФТИ",
        "desc": "Сильная школа ИИ, физики, биоинформатики.",
        "industry": "Вуз / Инжиниринг",
        "location": "Долгопрудный",
        "logo": "assets/logo/mipt.ru.png",
        "email": "industry@mipt.ru",
    },
    {
        "name": "Университет ИТМО",
        "desc": "Топ-вуз по ИТ и AI-проектам.",
        "industry": "Вуз / ИТ и фотоника",
        "location": "Санкт-Петербург",
        "logo": "assets/logo/itmo.ru.png",
        "email": "partnership@itmo.ru",
    },
    {
        "name": "НИУ ВШЭ",
        "desc": "Исследовательский университет с сильным бизнес-треком.",
        "industry": "Вуз / Экономика и ИТ",
        "location": "Москва",
        "logo": "assets/logo/hse.ru.png",
        "email": "partners@hse.ru",
    },
    {
        "name": "Сколтех",
        "desc": "Фокус на прикладных исследованиях и коммерциализации.",
        "industry": "Вуз / НИИ",
        "location": "Москва",
        "logo": "assets/logo/skoltech.ru.png",
        "email": "partnerships@skoltech.ru",
    },
    {
        "name": "НИТУ МИСИС",
        "desc": "Технологические решения для прома и энергетики.",
        "industry": "Вуз / Материаловедение",
        "location": "Москва",
        "logo": "assets/logo/misis.ru.png",
        "email": "industry@misis.ru",
    },
]
companies += [
    {
        "name": "НИЦ «Курчатовский институт»",
        "desc": "Комплекс уникальных установок, проекты Big Science.",
        "industry": "НИИ / Ядерные и междисциплинарные исследования",
        "location": "Москва",
        "logo": "assets/logo/nrcki.ru.png",
        "email": "partner@nrcki.ru",
    },
    {
        "name": "ИСП РАН",
        "desc": "Институт системного программирования, школа компиляторов и ИИ.",
        "industry": "НИИ / Программная инженерия",
        "location": "Москва",
        "logo": "assets/logo/ispras.ru.png",
        "email": "cooperation@ispras.ru",
    },
    {
        "name": "РГАУ-МСХА им. Тимирязева",
        "desc": "Аграрные исследования, опытные поля, цифровое земледелие.",
        "industry": "Аграрный вуз / НИОКР",
        "location": "Москва",
        "logo": "assets/logo/timacad.ru.png",
        "email": "partnership@timacad.ru",
    },
    {
        "name": "ФИЦ ВИР им. Н.И. Вавилова",
        "desc": "Мировая коллекция генетических ресурсов, проекты в агротехе.",
        "industry": "НИИ / Генетические ресурсы растений",
        "location": "Санкт-Петербург",
        "logo": "assets/logo/nrcki.ru.png",
        "email": "partner@vir.nw.ru",
    },
    {
        "name": "Росатом",
        "desc": "Госкорпорация полного ядерного цикла, крупные программы импортозамещения.",
        "industry": "Атомная энергетика / Машиностроение",
        "location": "Москва",
        "logo": "assets/logo/rosatom.ru.png",
        "email": "info@rosatom.ru",
    },
    {
        "name": "Ростех",
        "desc": "Госкорпорация с множеством отраслевых холдингов, фокус на высоких технологиях.",
        "industry": "Промышленность / Холдинг",
        "location": "Москва",
        "logo": "assets/logo/rostec.ru.png",
        "email": "info@rostec.ru",
    },
    {
        "name": "РЖД",
        "desc": "Национальный железнодорожный оператор с развитой ИТ-инфраструктурой.",
        "industry": "Транспорт / Логистика",
        "location": "Москва",
        "logo": "assets/logo/rzd.ru.png",
        "email": "info@rzd.ru",
    },
    {
        "name": "Аэрофлот",
        "desc": "Крупнейшая авиакомпания страны, сильный бренд и маркетинг.",
        "industry": "Авиация",
        "location": "Москва",
        "logo": "assets/logo/aeroflot.ru.png",
        "email": "public.relations@aeroflot.ru",
    },
]
companies += [
    {
        "name": "S7 Airlines",
        "desc": "Крупный частный авиаперевозчик, фокус на цифровых продуктах.",
        "industry": "Авиация",
        "location": "Москва / Новосибирск",
        "logo": "assets/logo/s7.ru.png",
        "email": "info@s7.ru",
    },
    {
        "name": "Газпромбанк",
        "desc": "Универсальный банк, активные программы для бизнеса.",
        "industry": "Банк / Финтех",
        "location": "Москва",
        "logo": "assets/logo/gazprombank.ru.png",
        "email": "info@gazprombank.ru",
    },
    {
        "name": "Россельхозбанк",
        "desc": "Банк с экосистемой для агросектора и МСП.",
        "industry": "Банк / Финтех",
        "location": "Москва",
        "logo": "assets/logo/rshb.ru.png",
        "email": "info@rshb.ru",
    },
    {
        "name": "Ингосстрах",
        "desc": "Один из лидеров страхового рынка, сильный бренд.",
        "industry": "Страхование",
        "location": "Москва",
        "logo": "assets/logo/ingos.ru.png",
        "email": "partners@ingos.ru",
    },
    {
        "name": "РЕСО-Гарантия",
        "desc": "Крупная универсальная страховая компания.",
        "industry": "Страхование",
        "location": "Москва",
        "logo": "assets/logo/reso.ru.png",
        "email": "partners@reso.ru",
    },
    {
        "name": "АльфаСтрахование",
        "desc": "Частный страховщик с развитой филиальной сетью.",
        "industry": "Страхование",
        "location": "Москва",
        "logo": "assets/logo/alfastrah.ru.png",
        "email": "partner@alfastrah.ru",
    },
    {
        "name": "X5 Group",
        "desc": "Группа «Пятёрочка», «Перекрёсток», цифровые сервисы и маркетинг.",
        "industry": "Ритейл / FMCG",
        "location": "Москва",
        "logo": "assets/logo/x5.ru.png",
        "email": "partners@x5.ru",
    },
    {
        "name": "Магнит",
        "desc": "Один из крупнейших ритейлеров страны.",
        "industry": "Ритейл / FMCG",
        "location": "Краснодар / Москва",
        "logo": "assets/logo/magnit.ru.png",
        "email": "partners@magnit.ru",
    },
]
companies += [
    {
        "name": "ВкусВилл",
        "desc": "Сеть магазинов здорового питания с сильной CRM и контент-маркетингом.",
        "industry": "Ритейл / Продукты",
        "location": "Москва",
        "logo": "assets/logo/vkusvill.ru.png",
        "email": "partners@vkusvill.ru",
    },
    {
        "name": "М.Видео-Эльдорадо",
        "desc": "Крупнейший ритейлер электроники с омниканалом.",
        "industry": "Ритейл / Электроника",
        "location": "Москва",
        "logo": "assets/logo/mvideo.ru.png",
        "email": "partners@mvideo.ru",
    },
    {
        "name": "DNS",
        "desc": "Федеральная сеть магазинов цифровой техники.",
        "industry": "Ритейл / Электроника",
        "location": "Владивосток",
        "logo": "assets/logo/dns-shop.ru.png",
        "email": "partner@dns-shop.ru",
    },
    {
        "name": "Ситилинк",
        "desc": "Один из лидеров онлайн-ритейла техники.",
        "industry": "Ритейл / Электроника",
        "location": "Москва",
        "logo": "assets/logo/citilink.ru.png",
        "email": "partners@citilink.ru",
    },
    {
        "name": "Hoff",
        "desc": "Федеральная сеть гипермаркетов мебели и товаров для дома.",
        "industry": "Ритейл / Мебель",
        "location": "Москва",
        "logo": "assets/logo/hoff.ru.png",
        "email": "partners@hoff.ru",
    },
    {
        "name": "O’Кей",
        "desc": "Сеть гипермаркетов и дискаунтеров.",
        "industry": "Ритейл / FMCG",
        "location": "Санкт-Петербург",
        "logo": "assets/logo/okmarket.ru.png",
        "email": "partners@okmarket.ru",
    },
    {
        "name": "Лента",
        "desc": "Федеральная сеть гипермаркетов и супермаркетов.",
        "industry": "Ритейл / FMCG",
        "location": "Санкт-Петербург",
        "logo": "assets/logo/lenta.com.png",
        "email": "partners@lenta.com",
    },
    {
        "name": "Петрович",
        "desc": "Сеть строительных магазинов и онлайн-платформа.",
        "industry": "DIY / Строительные материалы",
        "location": "Санкт-Петербург",
        "logo": "assets/logo/petrovich.ru.png",
        "email": "b2b@petrovich.ru",
    },
]
companies += [
    {
        "name": "ПИК",
        "desc": "Крупнейший девелопер жилой недвижимости.",
        "industry": "Девелопмент / Строительство",
        "location": "Москва",
        "logo": "assets/logo/pik.ru.png",
        "email": "partners@pik.ru",
    },
    {
        "name": "Самолёт",
        "desc": "Быстрорастущий девелопер с акцентом на ИТ-платформы.",
        "industry": "Девелопмент / Стройтех",
        "location": "Москва",
        "logo": "assets/logo/samolet.ru.png",
        "email": "partners@samolet.ru",
    },
    {
        "name": "ЛСР Групп",
        "desc": "Девелопер и производитель стройматериалов.",
        "industry": "Девелопмент / Строиматериалы",
        "location": "Санкт-Петербург",
        "logo": "assets/logo/lsrgroup.ru.png",
        "email": "info@lsrgroup.ru",
    },
    {
        "name": "Positive Technologies",
        "desc": "Российский вендор ИБ с продуктовой линейкой для бизнеса.",
        "industry": "Кибербезопасность",
        "location": "Москва",
        "logo": "assets/logo/ptsecurity.com.png",
        "email": "partners@ptsecurity.com",
    },
    {
        "name": "NAUMEN",
        "desc": "Разработчик сервис-десков, контакт-центров и аналитики.",
        "industry": "Корпоративный софт / SaaS",
        "location": "Екатеринбург",
        "logo": "assets/logo/naumen.ru.png",
        "email": "partner@naumen.ru",
    },
    {
        "name": "КРОК",
        "desc": "Крупный системный интегратор и облачный провайдер.",
        "industry": "ИТ-интеграция / Облака",
        "location": "Москва",
        "logo": "assets/logo/croc.ru.png",
        "email": "partners@croc.ru",
    },
    {
        "name": "T1",
        "desc": "Группа компаний с широким портфелем корпоративных решений.",
        "industry": "ИТ-интеграция / Связь",
        "location": "Москва",
        "logo": "assets/logo/t1.ru.png",
        "email": "partners@t1.ru",
    },
    {
        "name": "YADRO",
        "desc": "Российский производитель серверов и СХД, ИТ-инфраструктура.",
        "industry": "Оборудование / Дата-центры",
        "location": "Москва",
        "logo": "assets/logo/yadro.com.png",
        "email": "info@yadro.com",
    },
]
companies += [
    {
        "name": "СберМаркет",
        "desc": "Сервис доставки продуктов из сетей, развитая логистика.",
        "industry": "E-grocery / Доставка",
        "location": "Москва",
        "logo": "assets/logo/sbermarket.ru.png",
        "email": "partners@sbermarket.ru",
    },
    {
        "name": "Fix Price",
        "desc": "Федеральная сеть магазинов фиксированных цен.",
        "industry": "Ритейл / Дискаунтер",
        "location": "Москва",
        "logo": "assets/logo/fix-price.ru.png",
        "email": "partners@fix-price.ru",
    },
    {
        "name": "Совкомбанк",
        "desc": "Универсальный банк с активным маркетингом и программами для МСБ.",
        "industry": "Финтех / Банк",
        "location": "Москва",
        "logo": "assets/logo/sovcombank.ru.png",
        "email": "partners@sovcombank.ru",
    },
    {
        "name": "Точка Банк",
        "desc": "Онлайн-банк для предпринимателей с развитой экосистемой.",
        "industry": "Финтех / Банк для бизнеса",
        "location": "Москва",
        "logo": "assets/logo/tinkoff.ru.png",
        "email": "hello@tochka.com",
    },
    {
        "name": "YooMoney",
        "desc": "Платёжный сервис для бизнеса и частных лиц.",
        "industry": "Финтех / Платежи",
        "location": "Москва",
        "logo": "assets/logo/yoomoney.ru.png",
        "email": "b2b@yoomoney.ru",
    },
    {
        "name": "ЮKassa",
        "desc": "Провайдер онлайн-платежей для e-commerce.",
        "industry": "Финтех / Эквайринг",
        "location": "Москва",
        "logo": "assets/logo/yookassa.ru.png",
        "email": "merchants@yookassa.ru",
    },
    {
        "name": "QIWI",
        "desc": "Платёжная платформа и B2B-сервисы.",
        "industry": "Финтех / Платежи",
        "location": "Москва",
        "logo": "assets/logo/qiwi.com.png",
        "email": "partners@qiwi.com",
    },
    {
        "name": "ВСК",
        "desc": "Один из крупнейших страховщиков с широкой сетью.",
        "industry": "Страхование",
        "location": "Москва",
        "logo": "assets/logo/vsk.ru.png",
        "email": "partner@vsk.ru",
    },
]
companies += [
    {
        "name": "СОГАЗ",
        "desc": "Универсальный страховщик для крупного и среднего бизнеса.",
        "industry": "Страхование",
        "location": "Санкт-Петербург / Москва",
        "logo": "assets/logo/sogaz.ru.png",
        "email": "b2b@sogaz.ru",
    },
    {
        "name": "Делимобиль",
        "desc": "Крупный каршеринг с федеральным покрытием.",
        "industry": "Каршеринг / Mobility",
        "location": "Москва",
        "logo": "assets/logo/delimobil.ru.png",
        "email": "partners@delimobil.ru",
    },
    {
        "name": "BelkaCar",
        "desc": "Сервис поминутной аренды авто.",
        "industry": "Каршеринг",
        "location": "Москва",
        "logo": "assets/logo/belkacar.ru.png",
        "email": "partners@belkacar.ru",
    },
    {
        "name": "Whoosh",
        "desc": "Лидер кикшеринга с приложением и собственной телематикой.",
        "industry": "Шеринг e-скутеров",
        "location": "Москва",
        "logo": "assets/logo/whoosh.bike.png",
        "email": "partners@whoosh.bike",
    },
    {
        "name": "Яндекс Драйв",
        "desc": "Каршеринг и подписка на авто в экосистеме Яндекса.",
        "industry": "Каршеринг",
        "location": "Москва",
        "logo": "assets/logo/drive.yandex.ru.png",
        "email": "partner@drive.yandex.ru",
    },
    {
        "name": "Delivery Club",
        "desc": "Платформа заказов еды, широкая реклама и акции.",
        "industry": "Доставка еды",
        "location": "Москва",
        "logo": "assets/logo/delivery-club.ru.png",
        "email": "partners@delivery-club.ru",
    },
    {
        "name": "Утконос",
        "desc": "Онлайн-супермаркет с собственной логистикой.",
        "industry": "E-grocery",
        "location": "Москва",
        "logo": "assets/logo/utkonos.ru.png",
        "email": "b2b@utkonos.ru",
    },
    {
        "name": "Dodo Pizza",
        "desc": "Сеть пиццерий с сильным digital-маркетингом.",
        "industry": "Фудтех / Франчайзинг",
        "location": "Сыктывкар / Москва",
        "logo": "assets/logo/dodopizza.ru.png",
        "email": "partners@dodopizza.com",
    },
]
companies += [
    {
        "name": "Детский мир",
        "desc": "Крупнейший детский ритейлер с омниканалом.",
        "industry": "Ритейл / Детские товары",
        "location": "Москва",
        "logo": "assets/logo/detmir.ru.png",
        "email": "partners@detmir.ru",
    },
    {
        "name": "Спортмастер",
        "desc": "Федеральная сеть спортивного ритейла.",
        "industry": "Ритейл / Спорттовары",
        "location": "Москва",
        "logo": "https://logo.clearbit.com/sportmaster.ru?size=256",
        "email": "partners@sportmaster.ru",
    },
    {
        "name": "O’STIN",
        "desc": "Российский бренд повседневной одежды.",
        "industry": "Мода / Ритейл",
        "location": "Москва",
        "logo": "assets/logo/ostin.com.png",
        "email": "partners@ostin.com",
    },
    {
        "name": "Gloria Jeans",
        "desc": "Крупный fashion-ритейлер с активным SMM.",
        "industry": "Мода / Ритейл",
        "location": "Москва / Ростов-на-Дону",
        "logo": "assets/logo/gloria-jeans.ru.png",
        "email": "partners@gloria-jeans.ru",
    },
    {
        "name": "Kari",
        "desc": "Федеральная сеть обувных магазинов и ювелирного направления.",
        "industry": "Мода / Обувь и аксессуары",
        "location": "Москва",
        "logo": "assets/logo/kari.com.png",
        "email": "partners@kari.com",
    },
    {
        "name": "KazanExpress",
        "desc": "Быстрорастущий маркетплейс с региональной сетью ПВЗ.",
        "industry": "E-commerce / Маркетплейс",
        "location": "Казань",
        "logo": "assets/logo/kazanexpress.ru.png",
        "email": "partners@kazanexpress.ru",
    },
    {
        "name": "Petshop.ru",
        "desc": "Крупный онлайн-ритейлер товаров для животных.",
        "industry": "E-commerce / Зоотовары",
        "location": "Москва / Санкт-Петербург",
        "logo": "assets/logo/petshop.ru.png",
        "email": "b2b@petshop.ru",
    },
    {
        "name": "Apteka.ru",
        "desc": "Крупная онлайн-аптека с сетью пунктов выдачи.",
        "industry": "E-pharma",
        "location": "Москва",
        "logo": "assets/logo/apteka.ru.png",
        "email": "b2b@apteka.ru",
    },
]
companies += [
    {
        "name": "Skillbox",
        "desc": "Школа онлайн-курсов в ИТ/дизайне/маркетинге.",
        "industry": "EdTech",
        "location": "Москва",
        "logo": "assets/logo/skillbox.ru.png",
        "email": "b2b@skillbox.ru",
    },
    {
        "name": "Нетология",
        "desc": "Онлайн-университет цифровых профессий.",
        "industry": "EdTech",
        "location": "Москва",
        "logo": "assets/logo/netology.ru.png",
        "email": "b2b@netology.ru",
    },
    {
        "name": "GeekBrains",
        "desc": "Образовательная платформа VK по ИТ-направлениям.",
        "industry": "EdTech",
        "location": "Москва",
        "logo": "assets/logo/gb.ru.png",
        "email": "b2b@gb.ru",
    },
    {
        "name": "Skyeng",
        "desc": "Крупнейшая онлайн-школа английского и смежных дисциплин.",
        "industry": "EdTech / Языки и математика",
        "location": "Москва",
        "logo": "assets/logo/skyeng.ru.png",
        "email": "b2b@skyeng.ru",
    },
    {
        "name": "Яндекс Практикум",
        "desc": "Образовательная платформа Яндекса для подготовки ИТ-специалистов.",
        "industry": "EdTech / IT-обучение",
        "location": "Москва",
        "logo": "assets/logo/yandex.ru.png",
        "email": "partners@practicum.yandex.ru",
    },
    {
        "name": "ivi",
        "desc": "Стриминг-платформа с оригинальными проектами.",
        "industry": "Онлайн-кинотеатр",
        "location": "Москва",
        "logo": "assets/logo/ivi.ru.png",
        "email": "partners@ivi.ru",
    },
    {
        "name": "Okko",
        "desc": "Стриминг от экосистемы Сбера.",
        "industry": "Онлайн-кинотеатр",
        "location": "Москва",
        "logo": "assets/logo/okko.tv.png",
        "email": "partners@okko.tv",
    },
    {
        "name": "KION",
        "desc": "Видеосервис МТС с оригинальными сериалами.",
        "industry": "Онлайн-кинотеатр",
        "location": "Москва",
        "logo": "assets/logo/kion.ru.png",
        "email": "partners@kion.ru",
    },
]
